wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1642258212
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 2
      4: 3.8.3
      5: 0.12.9
      6: 4.15.0
      8:
      - 5
batch_size:
  desc: null
  value: 250
drop_out:
  desc: null
  value: 0.35
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: adam
