name: "Flake8 tests"

on:
  push:
    branches: [ main, ewelina ]
  pull_request:
    branches: [ main, ewelina ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Test with flake8
      run: |
        pip install flake8
        flake8 src/