name: "isort tests"

on:
  push:
    branches: [ main, ewelina ]
  pull_request:
    branches: [ main, ewelina ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Test aggremenet with isort
      run: |
        pip install isort
        isort .